
helper: helper.c thermal_state.m battery.h calendar.h cpu.h fan.h memory.h network.h smc.h temperature.h thermal_state.h power.h sketchybar.h
	clang -std=c99 -O3 -Wall -Wextra -Werror -framework IOKit -framework CoreFoundation -framework Foundation helper.c thermal_state.m -o helper
