# Shared by Zsh and Yazi.
# Reference: https://starship.rs/zh-CN/config/
"$schema" = "https://starship.rs/config-schema.json"

# 在 shell 提示符之间插入空行
add_newline = false

palette = 'gruvbox_dark'

command_timeout	= 1000

format = """
$os\
$all\
$fill\
$cmd_duration\
$line_break\
$jobs\
$battery\
$container\
$character
"""

[c]
symbol = " "
format = "[$symbol($version(-$name) )]($style)"

[character]
format = "$symbol"
success_symbol = "[❯](bold green) "
error_symbol = "[✗](bold red) "
vimcmd_symbol	= "[❮](bold yellow) "

[cmake]
symbol = "△ "
format = "[$symbol($version )]($style)"

[cmd_duration]
format = "[$duration]($style) "

[conda]
symbol = "🅒  "
format = "[$symbol$environment](bold green)"

[container]
symbol = " "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "
format = "[$symbol$context]($style)"

[fill]
symbol = " "

[git_branch]
symbol = ""
format = "[$symbol$branch(:$remote_branch)]($style)"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[java]
symbol = " "
format = "[${symbol}(${version} )]($style)"

[jobs]
symbol = "󰁯 "

[lua]
symbol = " "
format = "via [$symbol($version )]($style)"

[nodejs]
symbol = ""
format = "[$symbol($version )]($style)"

[os]
disabled = false
[os.symbols]
Amazon = " "
Android = " "
Arch = "󰣇 "
Debian = " "
Fedora = " "
Garuda = " "
Linux = " "
Macos = " "
Manjaro = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rlang]
symbol = " "
format = "[$symbol($version )]($style)"

[rust]
symbol = ""
format = "[$symbol($version )]($style)"

[palettes.gruvbox_dark]
black = '#282828'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
purple = '#d3869b'
cyan = '#8ec07c'
white = '#fbf1c7'

bright-black = '#928374'
bright-red = '#fb4934'
bright-green = '#b8bb26'
bright-yellow = '#fabd2f'
bright-blue = '#83a598'
bright-purple = '#d3869b'
bright-cyan = '#8ec07c'
bright-white = '#fbf1c7'
