#!/bin/bash

# General Icons
APPLE=􀣺
PREFERENCES=􀺽
ACTIVITY=􀒓
LOCK=􀒳
LOADING=􀖇

# System Widgets
export SYS_CPU_LOW=􀫥
export SYS_CPU_HIGH=􀧓
export SYS_MEM_LOW=􀫦
export SYS_MEM_HIGH=􀧖
export SYS_TEMP_LOW=􁏃
export SYS_TEMP_MEDIUM=􀇬
export SYS_TEMP_HIGH=􁏄
export SYS_POWER_LOW=􁌽
export SYS_POWER_HIGH=􁍀
export SYS_FAN_LOW=􁁋
export SYS_FAN_HIGH=􁁌
export SYS_FAN_STOP=􁝚

# Network
NETWORK_UP=􀆇
NETWORK_DOWN=􀆈

# Spaces
SPACE_SEPARATOR=􀆊

# Caffeinate
CAFFEINATE_1H=􀐱
CAFFEINATE_3H=􀐫
CAFFEINATE_6H=􀐬
CAFFEINATE_MIDNIGHT=􀆻
CAFFEINATE_NEXT_MORNING=􀷎
CAFFEINATE_CUSTOM=􀻧
CAFFEINATE_FOREVER=􀯠

# Yabai Icons
YABAI_STACK=􀏭
YABAI_FULLSCREEN_ZOOM=􀏜
YABAI_PARENT_ZOOM=􀥃
YABAI_FLOAT=􀢌

# Battery Icons (exported for the mach helper)
export BATTERY_100=􀛨
export BATTERY_75=􀺸
export BATTERY_50=􀺶
export BATTERY_25=􀛩
export BATTERY_0=􀛪
export BATTERY_CHARGING=􀢋

# Volume Icons
VOLUME_100=􀊩
VOLUME_66=􀊧
VOLUME_33=􀊥
VOLUME_10=􀊡
VOLUME_0=􀊣
VOLUME_AIRPODS_PRO=􀪷
VOLUME_SPEAKER=􀝏

VOLUME_HEADPHONES=􀑈
VOLUME_DISPLAY=􀢹
VOLUME_USB=􀺰
VOLUME_VIRTUAL=􀙫

# WiFi
WIFI_CONNECTED=􀙇
WIFI_DISCONNECTED=􀙈
