local options = {
  backup = false,                            -- no backup file
  clipboard = "unnamedplus",                 -- allows neovim to access the system clipboard
  cmdheight = 1,                             -- more space in the neovim command line for displaying messages
  completeopt = { "menuone", "noselect" },   -- mostly just for cmp
  conceallevel = 0,                          -- so that `` is visible in markdown files
  cursorline = true,                         -- highlight the current line
  expandtab = true,                          -- convert tabs to spaces
  fileencoding = "utf-8",                    -- the encoding written to a file
  foldexpr = "",                             -- set to "nvim_treesitter#foldexpr()" for treesitter based folding
  foldmethod = "manual",                     -- folding, set to "expr" for treesitter based folding
  guifont = "JetBrains_Mono,Hack_Nerd_Font", -- the font used in graphical neovim applications
  hidden = true,                             -- required to keep multiple buffers and open multiple buffers
  hlsearch = true,                           -- highlight all matches on previous search pattern
  ignorecase = true,                         -- ignore case in search patterns
  laststatus = 3,                            -- global statusline
  linebreak = true,                          -- companion to wrap, don't split words
  more = false,                              -- don't pause listing when screen is filled
  mouse = "a",                               -- allow the mouse to be used in neovim
  number = true,                             -- set numbered lines
  numberwidth = 2,                           -- set number column width to 2 {default 4}
  pumheight = 10,                            -- pop up menu height
  relativenumber = true,                     -- 相对行号
  ruler = false,
  scrolloff = 8,                             -- minimal number of screen lines to keep above and below the cursor.
  shadafile = join_paths(get_cache_dir(), "lvim.shada"),
  shiftwidth = 2,                            -- the number of spaces inserted for each indentation
  showmode = false,                          -- we don't need to see things like -- INSERT -- anymore
  showtabline = 2,                           -- always show tabs
  sidescrolloff = 8,                         -- minimal number of screen lines to keep left and right of the cursor.
  signcolumn = "yes",                        -- always show the sign column, otherwise it would shift the text each time
  smartcase = true,                          -- smart case
  smartindent = true,                        -- make indenting smarter again
  splitbelow = true,                         -- force all horizontal splits to go below current window
  splitright = true,                         -- force all vertical splits to go to the right of current window
  swapfile = false,                          -- creates a swapfile
  tabstop = 2,                               -- insert 2 spaces for a tab
  termguicolors = true,                      -- set term gui colors (most terminals support this)
  timeoutlen = 1000,                         -- time to wait for a mapped sequence to complete (in milliseconds)
  title = true,                              -- set the title of window to the value of the titlestring
  undodir = undodir,                         -- set an undo directory
  undofile = true,                           -- enable persistent undo
  updatetime = 100,                          -- faster completion (4000ms default)
  whichwrap = "bs<>[]hl",                    -- which "horizontal" keys are allowed to travel to prev/next line
  wrap = false,                              -- display lines as one long line
  writebackup = false,                       -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
}

for k, v in pairs(options) do
  vim.opt[k] = v
end
